import { StyleSheet } from 'react-native';
import { C } from './constants';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  container: { flex: 1, backgroundColor: C.bg, paddingHorizontal: 16 },

  // Header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 14,
    paddingBottom: 10,
    marginBottom: 4,
  },
  backBtn: { padding: 6, marginRight: 10 },
  backArrow: { fontSize: 22, color: C.text, fontWeight: '600' },
  headerTitle: { fontSize: 22, fontWeight: '700', color: C.text },

  sectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: C.sectionLabel,
    letterSpacing: 1.2,
    marginLeft: 4,
    marginBottom: 10,
    marginTop: 6,
  },

  // ── Notifications
  notifCard: {
    flexDirection: 'row',
    backgroundColor: C.card,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    shadowColor: C.cardShadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 3,
    alignItems: 'flex-start',
  },
  notifIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notifRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 3 },
  notifTitle: { fontSize: 14, fontWeight: '700', color: C.text, flex: 1 },
  notifTime: { fontSize: 11, color: C.textLight, marginRight: 6 },
  notifDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.dot },
  notifBody: { fontSize: 12.5, color: C.textSub, lineHeight: 18 },
  notifHighlight: { color: C.blue, fontWeight: '700' },

  // ── Profile
  profileAvatarWrap: { alignItems: 'center', marginTop: 8, marginBottom: 2 },
  profileAvatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: '#f0d9c8',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: C.white,
    shadowColor: C.cardShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  profileOnlineDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#4caf8c',
    borderWidth: 2.5,
    borderColor: C.bg,
    position: 'absolute',
    bottom: 4,
    right: '42%',
  },
  profileName: { textAlign: 'center', fontSize: 20, fontWeight: '700', color: C.text, marginTop: 10 },
  profileHandle: { textAlign: 'center', fontSize: 13, color: C.textSub, marginBottom: 16 },
  profileCard: {
    backgroundColor: C.card,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 10,
    shadowColor: C.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  profileRow: { flexDirection: 'row', alignItems: 'center' },
  profileIconBox: { width: 38, height: 38, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  profileRowLabel: { flex: 1, fontSize: 15, fontWeight: '600', color: C.text },
  profileRowSub: { fontSize: 12, color: C.textLight, marginTop: 2 },
  profileRowAction: { fontSize: 13, color: C.textSub, fontWeight: '600' },

  tabRow: {
    flexDirection: 'row',
    borderBottomWidth: 1.5,
    borderBottomColor: C.border,
    marginBottom: 14,
    marginTop: 6,
  },
  tab: { flex: 1, paddingBottom: 10, alignItems: 'center' },
  tabActive: { borderBottomWidth: 2.5, borderBottomColor: C.blue },
  tabText: { fontSize: 14, color: C.textSub, fontWeight: '500' },
  tabTextActive: { color: C.blue, fontWeight: '700' },

  msgCard: {
    backgroundColor: C.card,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    shadowColor: C.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 2,
  },
  msgCardMe: { backgroundColor: '#f0f6fd' },
  msgHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  msgSender: { fontSize: 11, fontWeight: '800', color: C.blue, letterSpacing: 0.5, flex: 1 },
  msgTime: { fontSize: 10.5, color: C.textLight },
  msgText: { fontSize: 13, color: C.text, lineHeight: 19 },
  unstarBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#fff0f3',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#f9b8c4',
  },
  unstarText: { color: C.red, fontSize: 12, fontWeight: '600' },

  // ── New List
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.card,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    marginBottom: 18,
    shadowColor: C.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 2,
  },
  searchInput: { flex: 1, fontSize: 14, color: C.text },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.card,
    borderRadius: 16,
    padding: 13,
    marginBottom: 10,
    shadowColor: C.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 2,
  },
  contactAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contactInitials: { color: C.white, fontWeight: '700', fontSize: 15 },
  contactName: { fontSize: 14.5, fontWeight: '700', color: C.text },
  contactSub: { fontSize: 12, color: C.textSub, marginTop: 2 },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1.8,
    borderColor: C.border,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: C.bg,
  },
  checkboxSelected: {
    backgroundColor: C.blue,
    borderColor: C.blue,
  },
  selectedBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: C.card,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: 20,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: C.cardShadow,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 10,
  },
  selectedChip: { alignItems: 'center' },
  selectedChipAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chipClose: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: C.text,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chipName: { fontSize: 10, color: C.textSub, marginTop: 3 },
  selectedCount: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: C.border,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedCountText: { color: C.blue, fontWeight: '700', fontSize: 15 },
  createBtn: { color: C.blue, fontWeight: '700', fontSize: 16 },

  // ── Report Sent
  reportFormWrap: { opacity: 0.4, marginTop: 20 },
  reportLabel: { fontSize: 11, fontWeight: '700', color: C.sectionLabel, letterSpacing: 1, marginBottom: 8 },
  reportSelect: {
    backgroundColor: C.card,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reportSelectText: { color: C.textLight, fontSize: 14 },
  reportTextarea: {
    backgroundColor: C.card,
    borderRadius: 12,
    padding: 14,
    height: 100,
    justifyContent: 'flex-start',
  },
  reportSubmitBtn: {
    backgroundColor: C.blue,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 20,
  },
  reportSubmitText: { color: C.white, fontWeight: '700', fontSize: 15 },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  modalCard: {
    backgroundColor: C.white,
    borderRadius: 24,
    paddingHorizontal: 28,
    paddingTop: 36,
    paddingBottom: 28,
    alignItems: 'center',
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 12,
  },
  modalCheckWrap: { marginBottom: 20 },
  modalCheckRing: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(76,175,140,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCheckCircle: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: C.green,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: { fontSize: 22, fontWeight: '800', color: C.text, marginBottom: 10 },
  modalBody: { fontSize: 13.5, color: C.textSub, textAlign: 'center', lineHeight: 20, marginBottom: 24 },
  modalDoneBtn: {
    backgroundColor: C.blue,
    borderRadius: 30,
    paddingVertical: 14,
    paddingHorizontal: 80,
    width: '100%',
    alignItems: 'center',
  },
  modalDoneText: { color: C.white, fontWeight: '700', fontSize: 16 },

  // ── Settings
  settingCard: {
    backgroundColor: C.card,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 6,
    marginBottom: 6,
    shadowColor: C.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  settingIconBox: {
    width: 38,
    height: 38,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  settingLabel: { flex: 1, fontSize: 14.5, fontWeight: '600', color: C.text },
  settingHint: { fontSize: 11.5, color: C.textLight, marginLeft: 50, marginBottom: 6 },
  settingDivider: { height: 1, backgroundColor: C.border, marginLeft: 50 },
  settingsFooter: {
    fontSize: 12,
    color: C.textSub,
    textAlign: 'center',
    marginTop: 24,
    lineHeight: 18,
    paddingHorizontal: 10,
  },

  // ── Home
  homeContent: { paddingHorizontal: 24, paddingTop: 60, paddingBottom: 40 },
  homeTitle: { fontSize: 28, fontWeight: '800', color: C.text, marginBottom: 6, textAlign: 'center' },
  homeSub: { fontSize: 14, color: C.textSub, textAlign: 'center', marginBottom: 30 },
  homeCard: {
    backgroundColor: C.card,
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 18,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: C.cardShadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  homeCardText: { fontSize: 16, fontWeight: '700', color: C.text },

  // ── Communities
  communitySection: {
    marginBottom: 18,
  },
  communitySectionLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    gap: 7,
  },
  communityDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  communitySectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: C.sectionLabel,
    letterSpacing: 0.8,
  },
  communityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.card,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 10,
    shadowColor: C.cardShadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  communityCardIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  communityCardName: {
    fontSize: 15.5,
    fontWeight: '700',
    color: C.text,
    marginBottom: 3,
  },
  communityCardRole: {
    fontSize: 11,
    fontWeight: '600',
    color: C.sectionLabel,
    letterSpacing: 0.5,
  },

  // ── Add New Data
  uploadBox: {
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderRadius: 20,
    borderWidth: 1.8,
    borderColor: '#a8d4f0',
    borderStyle: 'dashed',
    paddingVertical: 32,
    alignItems: 'center',
    marginBottom: 28,
    shadowColor: C.cardShadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2,
  },
  uploadIconWrap: {
    position: 'relative',
    marginBottom: 14,
    alignItems: 'center',
    justifyContent: 'center',
    width: 64,
    height: 64,
  },
  uploadArrow: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: C.blue,
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadTitle: { fontSize: 18, fontWeight: '700', color: C.text, marginBottom: 6 },
  uploadSub: { fontSize: 13, color: C.textSub, textAlign: 'center', lineHeight: 19 },
  sectionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  viewAll: { fontSize: 13, color: C.blue, fontWeight: '600' },
  fileCard: {
    flexDirection: 'row',
    backgroundColor: C.card,
    borderRadius: 18,
    padding: 15,
    marginBottom: 12,
    alignItems: 'center',
    shadowColor: C.cardShadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 3,
  },
  fileIconBox: {
    width: 46,
    height: 46,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fileName: { fontSize: 15, fontWeight: '700', color: C.text, marginBottom: 2 },
  fileMeta: { fontSize: 11.5, color: C.textLight, marginBottom: 8 },
  fileStats: { flexDirection: 'row', alignItems: 'center' },
  statItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  statIcon: { fontSize: 12 },
  statText: { fontSize: 12, color: C.textSub, fontWeight: '500' },
  moreBtn: { padding: 6, alignSelf: 'flex-start' },
});
